# Generated by Django 5.0.4 on 2024-05-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "sponsor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="portal.legislator",
                        verbose_name="Primary sponsor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="portal.bill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vote_type", models.IntegerField(choices=[(1, "Yea"), (2, "Nay")])),
                (
                    "legislator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="portal.legislator"
                    ),
                ),
                (
                    "vote_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="portal.vote"
                    ),
                ),
            ],
        ),
    ]
