# Generated by Django 5.0.4 on 2024-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="title",
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
